# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Tor Inge Jøssang
tagline:             'prosjekter'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://lanyon.getpoole.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Tor Inge Jøssang
  url:               https://twitter.com/torjossang
  email:             tor.jossang@gmail.com

# Custom vars
version:             1.0.0
